### ISSUE TITLE
Set up WordPress boilerplate

### ISSUE THREAD

**Issue by vanessasickles** [vanessasickles/urpg-theme-2020#1]
## Overview
This issue addresses setting up my preferred WordPress defaults.

## Tasks
- [x] Set up default templates
- [x] Set up default `functions.php`
- [x] Install and activate default plugins
