### ISSUE TITLE
 Build Header & Navigation

### ISSUE THREAD

**Issue by vanessasickles** [vanessasickles/urpg-theme-2020#8]
# Overview
This task covers building and styling the initial prototypes of the header and navigation.

## Tasks
* [ ] Insert main WordPress menu
* [ ] Build and style for desktop
* [ ] Build JS for menu open/close on mobile
* [ ] Build and style for mobile

## Notes
This is the initial build to fit the design; this especially will need heavy work with Elrond to mesh with his functionality. For now, it should be built stand-alone.
